### PR TITLE
Added background-color to the main body

### PR DESCRIPTION
**Pull request by SuitIThub**
Added background-color to have a consistent background color across different scenarios. For example to make it more usable in Vivaldis Side-Web-Panel, where the windows stretches across the full height of the browser.

Before:
Before

After:
After

### CODE REVIEW

**Comment by Klemms** [comment]
Hi, I didn't know this web browser existed ! Thanks for the PR, I may look around to see if other improvements are possible to make the experience better on this.

**Comment by SuitIThub** [comment]
yeah it's a nice browser where you can customise pretty much everything :D
But nice. one thing I noticed was that the different ui elements don't scale with the with of the window :)

**Comment by Klemms** [comment]
I did some further changes, gonna upload it for review to the chrome webstore soon

**Comment by Klemms** [comment]
This should fix all scaling and elements size issues

**Pull request merged**
